### ISSUE TITLE
kfocus-mime fails to launch KeePassXC when attempting to launch it from an xterm script or Qt Quick app

### ISSUE THREAD

**Issue by ArrayBolt3** [kfocus/kfocus-source#12]
**Describe the bug**
When attempting to launch KeePassXC via `bash -c kfocus-mime -k keepassxc`, sometimes the script exits quickly without actually launching the app. This doesn't ever happen (that I know of) when running the command from a terminal, and it doesn't happen if KeePassXC is already running in the background, but it happens every single time when using QProcess to launch the app, and it can also be reproduced via the following odd xterm script maneuver.

**To Reproduce**
1. Ensure that KeePassXC is entirely closed (not running in the system tray).
2. Create a script named `test.sh`, and populate it with the following code:
```
#!/bin/bash
kfocus-mime -k keepassxc
```
3. Set the script as executable (`chmod +x ./test.sh`).
4. Run `xterm ./test.sh`.
5. The xterm window will appear briefly and then close, without running KeePassXC.

**Expected behavior**
KeePassXC should launch normally.

**Desktop (please complete the following information):**
 - OS: Kubuntu 22.04 LTS with Focus enhancements

**Additional context**
If I open the kfocus-mime script using `sudo vim /usr/lib/kfocus/bin/kfocus-mime`, and go to [line 770](https://github.com/kfocus/kfocus-source/blob/JJ-2023-07/package-main/usr/lib/kfocus/bin/kfocus-mime#L770), I can remove the ampersand at the end of this line, save the script, and then run the above steps again. KeePassXC will launch normally this time. However, the xterm window will remain open as the KeePassXC process is no longer being backgrounded. This also allows a Qt Quick app to launch KeePassXC. This change may have profound effects on other apps in the KFocus ecosystem that expect kfocus-mime to be non-blocking, so I don't believe this is a suitable bugfix on its own. However, it may be possible to add an extra command-line switch that enables this blocking mode. Then apps that need to run KeePassXC but that can't normally can use the alternate switch, and cope with the blocking behavior themselves.

**Comment by mmikowski** [comment]
The current implementation of kfocus-mime is to support launching from curated apps. 

* We will want to ensure this is working as expected when kfocus-mime is asked to run KeePassXC using the curated apps [web page](https://kfocus.org/wf/apps). We should verify (in a VM), execution when it is not installed, not running, and is running. These tests have been done many times before, but KeePassXC may have changed subtly after a recent upgrade.
* The last known status was that kfocus-mime worked as expected with the launch. However, recognize kfocus-mime is registered as a browser helper app, and is NOT invoked with kfocus-mime -k, but instead reads and processes an external <name>.kfocus-001 file. Although unlikely, this might cause this difference.
* We may be able to apply a flag to prevent the run-in-the-background behavior (e.g. kfocus-mime -kf keepassxc) where -f means "force-foreground".

The last point seems like the most promising and safest solution.

**Comment by ArrayBolt3** [comment]
I've implemented the solution in the third bullet point (the `-kf` switch) in the 3613_2023-07-24_qml-welcome branch and verified that it works.

**Comment by mmikowski** [comment]
Since we have a work around, closing this ticket.
