### ISSUE TITLE
_cm2RunLongCmdFn errors out with an unbound variable error if zenity is not installed and `set -u` is active

### ISSUE THREAD

**Issue by ArrayBolt3** [kfocus/kfocus-source#15]
**Describe the bug**
If zenity is not installed on the system, using `_cm2RunLongCmdFn` in a script that uses `set -u` will error out with `./common.2.source: line 161: _exit_str: unbound variable`.

**To Reproduce**
1. Install plain Kubuntu 22.04 LTS into a VM.
2. Get the `common.2.source` file into the VM and place it in your home directory within the VM.
3. Create a script, `launcher.sh` in your home directory within the VM, with the following contents:

```
#!/bin/bash
set -u;
source $HOME/common.2.source;
_cm2RunLongCmdFn "test" "$HOME/sleep.sh";
```

4. Create a script, `sleep.sh` in your home directory within the VM, with the following contents:

```
#!/bin/bash
sleep 10;
```

5. `chmod +x` both `launcher.sh` and `sleep.sh`.
6. Run `./launcher.sh`.
7. Provide your admin password when prompted.

**Expected behavior**
The script should pause for 10 seconds, then return without errors.

**Desktop:**
 - OS: Kubuntu 22.04.3 (NOT Kubuntu Focus Suite)

**Additional context**
By looking through the code of common.2.source, it appears that the function always attempts to run `echo "${_exit_str}"` just before returning. However `_exit_str` is only assigned a value if the long-running command is executed using pkexec and zenity. When zenity doesn't exist, a different code path is followed that only uses pkexec, and that code path does not set `_exit_str`. Thus when the function attempts to echo `_exit_str`'s value, the error occurs.

I was able to resolve the issue by simply moving the `echo "${_exit_str}";` line into the code block that uses zenity, immediately before the closing `fi`. I don't *think* this will have any adverse effects. I'll try that, run a regression test, and submit a PR if it works.

This bug was discovered during the development of the kfocus-enhancement-installer, which is designed to run in an environment where Kubuntu Focus enhancements are not present.

**Comment by mmikowski** [comment]
Thank you Aaron.

We do want to always echo a string, even if it's empty. Here are three options:

1. Set _exit_str='' at the top as the default.
2. Apply and else clause which sets _exit_str
3. Enclose the echo inside of the if clause (as in the PR)
4. Use `echo "${_exit_str:-}"` which will never fail

Of these 4, I believe 1 + 4 are good, fail-safe methods that would fix the issue with the fewest changes, clarity, and durability.

**Comment by ArrayBolt3** [comment]
ah, so to be clear, even if the non-zenity code path is followed, we should still echo an (empty) string? If so, I agree with you on using options 1 + 4. If you'd like to do that, great, otherwise I'll update my PR with the other fix.

**Comment by ArrayBolt3** [comment]
Just pushed the alternate fix to my PR, now options 1 and 4 are both used.
