### ISSUE TITLE
kfocus-keyboard fails to build on linux kernel >= 6.4

### ISSUE THREAD

**Issue by FeatherAntennae** [kfocus/kfocus-source#17]
**Describe the bug**
The kfocus-keyboard package fails to build on more recent Linux kernels due to a breaking change introduced around 6.4. This also cause the configuration of kfocus-power-fan or any other package depending on kfocus-keyboard to fail.

Calls to `class_create(...)` in `tuxedo_io/tuxedo_io.c` need to be modified, as the function doesn't take a pointer anymore, only the name of the class.

On a side note: When done automatically through FocusRx or the first boot config, the utility fails to detect the error and simply asks to reboot to complete the setup, then does the same thing on every subsequent boot.

**To Reproduce**
Steps to reproduce the behaviour:
A)
1. sudo apt-get install kfocus-keyboard
2. Errors appear in console

B)
1. Use FocusRx or first run utility to set up for hardware
2. Accept reboot request
3. Utility runs and asks to reboot again
4. Back to step B) 2.

**Expected behavior**
- The packages should successfully compile and install
- Hardware setup should detect if a dkms module failed to build or an error has kept the setup from completing.

**Screenshots**
![image](https://github.com/kfocus/kfocus-source/assets/52422077/d347b718-9f7f-424c-91d2-8d8703915f46)
(Also see [make.log](https://github.com/kfocus/kfocus-source/files/13831942/make.log))

**Desktop (please complete the following information):**
 - Any version of Kubuntu using a kernel >= 6.4
 - Tested on the M2G5

**Additional context**
I understand the current support is for Kubuntu 22.04 LTS only, but I thought I'd give a heads-up with the upcoming 24.04 LTS release. I added the `make.log` file with the error for reference.

I believe the commit that introduced the change is this one:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/drivers/base/class.c?id=dcfbb67e48a2becfce7990386e985b9c45098ee5

**Comment by ArrayBolt3** [comment]
Thank you, this is very helpful! We'll keep an eye on this and use the info here to get kfocus-keyboard working on newer kernels once we start working on Kubuntu Focus Suite 24.04.

**Comment by mmikowski** [comment]
@FeatherAntennae we have implemented and are testing an update for 6.5 and earlier kernels. It appears the breaking change occurred in kernel 6.4, although this will need to be verified. 

The HWE 6.5.x hwe kernel just dropped today for 22.04 LTS. This is being tested for all hardware. If all regression and hardware tests pass, the kernel package is likely to be released around the same time (1-2 weeks). If the kernel does not pass but the keyboard package does, we'll likely publish an updated package sooner.

Thanks again for your help in identifying this!

**Comment by mmikowski** [comment]
Internal ticket 4002. Beta package submitted to kfocus-team/package-testing (building). Verified the break-point is kernel 6.4.

**Comment by mmikowski** [comment]
@FeatherAntennae The fix was applied and released 2024-01-27.
