### ISSUE TITLE
Currated App: Docker - does not set user on group

### ISSUE THREAD

**Issue by ricktimmis** [kfocus/kfocus-source#20]
**Describe the bug**
With Docker installed via the Currated Apps page, on KFocus M2 Gen the installing user is not added to the docker group. Leading to errors like:

`Building the docker image...
ERROR: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Head "http://%2Fvar%2Frun%2Fdocker.sock/_ping": dial unix /var/run/docker.sock: connect: permission denied`

**To Reproduce**
1. Go to 'Kicker > Kubuntu Focus Tools > Currated Apps '
2. Opens in browser
3. Scroll down to 'Docker'
4. Konsole opens and installs docker
5. Logout / Reboot
6. Try to use Docker, get error

**Expected behavior**
Once installed by the user, then post logout/reboot the users should have permission to use Docker. Likely that 
`usermod -aG $USER Docker` needs to be run

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Kubuntu Focus 22.04
 - Browser: Chrome 

**Additional context**
Hope this is a useful report

**Comment by mmikowski** [comment]
Hi Rick:

Thank you for this report. Yes, it is useful. We have an internal tracking ticket for the same issue. The default install currently is root only and does not take the extra steps to make it "user runnable". That requires a special wrapper which has not yet been written for docker-ce, although it is covered in the docs found in the curated apps page.

Internal ticket #2068.

Cheers, Mike

**Comment by ArrayBolt3** [comment]
A fix for this issue has been uploaded to the package-testing repository for both Jammy and Noble. Assuming all tests pass, it should be generally available in the release repository in the coming days.

**Comment by mmikowski** [comment]
This enhancement was released for 22.04 and 24.04 around 21 June 2024.
